### ISSUE TITLE
Errors on trying new images

### ISSUE THREAD

**Issue by hacksider** [sammdu/pyimgscan#1]
Traceback (most recent call last):
  File "./pyimgscan.py", line 156, in <module>
    corners = getcorners(img_hull)
  File "./pyimgscan.py", line 141, in getcorners
    return corners
UnboundLocalError: local variable 'corners' referenced before assignment

**Comment by hacksider** [comment]
![image](https://user-images.githubusercontent.com/1267200/74731671-6c562600-5283-11ea-9067-751b28bfe739.png)

**Comment by hacksider** [comment]
![image](https://user-images.githubusercontent.com/1267200/74731747-a45d6900-5283-11ea-98ad-34496e3cb094.png)

**Comment by hacksider** [comment]
Sample image tested is this
![image](https://user-images.githubusercontent.com/1267200/74731848-df5f9c80-5283-11ea-9451-7befdfc23d6d.png)

**Comment by sammdu** [comment]
Ah, it happens sometimes, when the algorithm cannot find 4 corners in the first place. I'll look into it more, and perhaps print a traceback that makes more sense. 

The long term goal is, of course, to always find 4 corners, especially in this type of image where it seems like the edges of the paper is pretty visible.

I'm going to guess that there isn't enough contrast between the paper and the background for the algorithm at the current stage, so the contours are weak, therefore corners not found.

I'll test your image when I get some time, and let you know exactly what went wrong. Thanks for the feedback!

**Comment by sammdu** [comment]
@hacksider I tested your image and it indeed got overexposed during the adjustment phase and lost its contour.
I need to come up with a better pre-processing algorithm so that the contours are best preserved. If you can pre-process your image so that there is more contrast, like this:

![image](https://user-images.githubusercontent.com/10665890/74743283-1c00a900-522e-11ea-9212-447d0684977b.png)

That will fix the issue.

**Comment by hacksider** [comment]
Awesome! Thanks for the tips! By the way, the app is amazing and is a life saver! Really loved the implementation! Kudos to you!
